#!/bin/bash

color="red"

case $color in
    blue)
        echo "You chose blue."
        ;;
    green)
        echo "You chose green."
        ;;
    red)
        echo "You chose red."
        ;;
    *)
        echo "Unknown color."
        ;;
esac
